// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDvJbq-l6ogfExRt4rclUKoMvaiJzbanM',
    appId: '1:351937924229:web:29fa82aeec555713beedec',
    messagingSenderId: '351937924229',
    projectId: 'flutterprojectapp-70631',
    authDomain: 'flutterprojectapp-70631.firebaseapp.com',
    storageBucket: 'flutterprojectapp-70631.firebasestorage.app',
    measurementId: 'G-PXR2Q124WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFoiEfJpGz8tWTRNYYicWSUDMr_tWC6RM',
    appId: '1:351937924229:android:4599aa9e558bc086beedec',
    messagingSenderId: '351937924229',
    projectId: 'flutterprojectapp-70631',
    storageBucket: 'flutterprojectapp-70631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmm8OjDKKGnPl1T37W1qAZvKt5tPxu_7g',
    appId: '1:351937924229:ios:b3261f56bbc7306abeedec',
    messagingSenderId: '351937924229',
    projectId: 'flutterprojectapp-70631',
    storageBucket: 'flutterprojectapp-70631.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectApp',
  );
}
